fileVersion: 1
id: "13"
mappingDefinitions:
  SRC:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  TARGET:
    database: SNEHAL_DB
    schema: INFORMATION_SCHEMA
  WORK:
    database: SNEHAL_DB
    schema: PUBLIC
name: Dummy Environment
type: Environment
