fileVersion: 1
id: "7"
mappingDefinitions:
  SRC:
    database: WANI
    schema: SRC
  TARGET:
    database: WANI
    schema: TARGET
  WORK:
    database: WANI
    schema: WORKPROD
name: Production Environment
type: Environment
